// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Resync = require("refetch/src/Resync.bs.js");
var Refetch = require("refetch/src/Refetch.bs.js");
var Readline = require("readline");
var Refetch__Request = require("refetch/src/Refetch__Request.bs.js");
var Refetch__Response = require("refetch/src/Refetch__Response.bs.js");
var IsoFetch$RefetchSetup = require("../IsoFetch.bs.js");

var consumer_key = "bDVlFjkYD7v4WkKIuu5AbCjSr";

var consumer_secret = "J2tALuP5nuGzuc1mtZ281tOlRnGW5Vp5fPprYUT2xSVwpNJ2Is";

var requestTokenURL = "https://api.twitter.com/oauth/request_token";

var oAuthConfig = {
  callback: "oob",
  consumer_key: consumer_key,
  consumer_secret: consumer_secret
};

var oauth = {
  oauth: {
    callback: "oob",
    consumer_key: consumer_key,
    consumer_secret: consumer_secret
  }
};

var oauthJson = oauth.oauth;

console.log("oauthJson", oauthJson);

var requestTokenJson = {
  url: requestTokenURL,
  oauth: oauthJson
};

console.log("requestTokenJson", requestTokenJson);

console.log("oAuthConfigJson", requestTokenJson);

var options_input = (process.stdin);

var options_output = (process.stdout);

var options = {
  input: options_input,
  output: options_output,
  terminal: undefined,
  historySize: undefined,
  prompt: undefined,
  crlfDelay: undefined,
  removeHistoryDuplicates: undefined
};

var readline = Readline.createInterface(options);

function read(param) {
  readline.question("cli> ", param);
  return /* () */0;
}

function cli(param) {
  return read((function (line) {
                console.log("line", line);
                return cli(/* () */0);
              }));
}

Resync.Future.whenResolved((function (prim) {
        console.log(prim);
        return /* () */0;
      }), Resync.Future.flatMap((function (param) {
            if (param.tag) {
              return Resync.Future.from(param[0].reason);
            } else {
              return Curry._1(Refetch__Response.text, param[1]);
            }
          }), Refetch.$$fetch(Refetch__Request.payload(/* `Json */[
                  826371656,
                  requestTokenJson
                ], Refetch.request(/* POST */891112544, undefined, undefined, undefined, requestTokenURL)))));

var oAuthConfigJson = requestTokenJson;

exports.consumer_key = consumer_key;
exports.consumer_secret = consumer_secret;
exports.requestTokenURL = requestTokenURL;
exports.oAuthConfig = oAuthConfig;
exports.oauth = oauth;
exports.oauthJson = oauthJson;
exports.requestTokenJson = requestTokenJson;
exports.oAuthConfigJson = oAuthConfigJson;
exports.options = options;
exports.readline = readline;
exports.read = read;
exports.cli = cli;
/* oauthJson Not a pure module */
