// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var SimpleGet$RefetchSetup = require("./simpleGet.bs.js");
var SimplePost$RefetchSetup = require("./simplePost.bs.js");

console.log("SimplePost");

console.log("SimpleGet");

/*  Not a pure module */
