// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Resync = require("refetch/src/Resync.bs.js");
var Refetch = require("refetch/src/Refetch.bs.js");
var Refetch__Request = require("refetch/src/Refetch__Request.bs.js");
var Refetch__Response = require("refetch/src/Refetch__Response.bs.js");

require('isomorphic-fetch')
;

Resync.Future.whenResolved((function (prim) {
        console.log(prim);
        return /* () */0;
      }), Resync.Future.flatMap((function (param) {
            if (param.tag) {
              return Resync.Future.from(param[0].reason);
            } else {
              return Curry._1(Refetch__Response.text, param[1]);
            }
          }), Refetch.$$fetch(Refetch__Request.payload(/* `Multipart */[
                  -1031569716,
                  /* tuple */[
                    "booboo",
                    /* :: */[
                      /* tuple */[
                        /* :: */[
                          /* `ContentType */[
                            246273139,
                            "plain/text"
                          ],
                          /* :: */[
                            /* `ContentDisposition */[
                              -378039458,
                              /* tuple */[
                                /* `Other */[
                                  -912009552,
                                  "form-data"
                                ],
                                /* :: */[
                                  /* `Other */[
                                    -912009552,
                                    /* tuple */[
                                      "name",
                                      "field1"
                                    ]
                                  ],
                                  /* :: */[
                                    /* `Filename */[
                                      -786699545,
                                      "myimage.png"
                                    ],
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ],
                            /* [] */0
                          ]
                        ],
                        /* `String */[
                          -976970511,
                          "foo"
                        ]
                      ],
                      /* :: */[
                        /* tuple */[
                          /* :: */[
                            /* `ContentType */[
                              246273139,
                              "application/json"
                            ],
                            /* :: */[
                              /* `ContentDisposition */[
                                -378039458,
                                /* tuple */[
                                  /* `Other */[
                                    -912009552,
                                    "form-data"
                                  ],
                                  /* :: */[
                                    /* `Other */[
                                      -912009552,
                                      /* tuple */[
                                        "name",
                                        "field1"
                                      ]
                                    ],
                                    /* [] */0
                                  ]
                                ]
                              ],
                              /* [] */0
                            ]
                          ],
                          /* `Json */[
                            826371656,
                            null
                          ]
                        ],
                        /* [] */0
                      ]
                    ]
                  ]
                ], Refetch.request(/* GET */3546230, undefined, undefined, undefined, "http://httpbin.org/post")))));

/*  Not a pure module */
