// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Resync = require("refetch/src/Resync.bs.js");
var Refetch = require("refetch/src/Refetch.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var ConsolePng = require("console-png");
var StreamToBuffer = require("stream-to-buffer");
var Refetch__Response = require("refetch/src/Refetch__Response.bs.js");
var IsoFetch$RefetchSetup = require("./IsoFetch.bs.js");

Resync.Future.whenCompleted((function (param) {
        if (param.tag) {
          console.log(param[0]);
          return /* () */0;
        } else {
          StreamToBuffer(param[0], (function (param, buffer) {
                  ConsolePng(buffer, (function (param, string) {
                          console.log(string);
                          return /* () */0;
                        }));
                  return /* () */0;
                }));
          return /* () */0;
        }
      }), Resync.Future.map((function (param) {
            if (param.tag) {
              return Pervasives.failwith(param[0].reason);
            } else {
              return Refetch__Response.body(param[1]);
            }
          }), Refetch.get("http://httpbin.org/image/png")));

/*  Not a pure module */
