// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Resync = require("refetch/src/Resync.bs.js");
var Refetch = require("refetch/src/Refetch.bs.js");
var Refetch__Request = require("refetch/src/Refetch__Request.bs.js");
var Refetch__Response = require("refetch/src/Refetch__Response.bs.js");

require('isomorphic-fetch')
;

Resync.Future.whenResolved((function (prim) {
        console.log(prim);
        return /* () */0;
      }), Resync.Future.flatMap((function (param) {
            if (param.tag) {
              return Resync.Future.from(param[0].reason);
            } else {
              return Curry._1(Refetch__Response.text, param[1]);
            }
          }), Refetch.$$fetch(Refetch__Request.payload(/* `Form */[
                  781815140,
                  /* :: */[
                    /* tuple */[
                      "foo",
                      "boo"
                    ],
                    /* :: */[
                      /* tuple */[
                        "bar",
                        "far"
                      ],
                      /* [] */0
                    ]
                  ]
                ], Refetch.request(/* POST */891112544, undefined, undefined, undefined, "http://httpbin.org/post")))));

/*  Not a pure module */
