// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Resync = require("refetch/src/Resync.bs.js");
var Refetch = require("refetch/src/Refetch.bs.js");
var Refetch__Response = require("refetch/src/Refetch__Response.bs.js");

require('isomorphic-fetch')
;


  const debugHttp = require('debug-http');
  debugHttp();

;

Resync.Future.whenResolved((function (text) {
        console.log(text);
        return /* () */0;
      }), Resync.Future.flatMap((function (param) {
            if (param.tag) {
              return Resync.Future.from(param[0].reason);
            } else {
              return Curry._1(Refetch__Response.text, param[1]);
            }
          }), Refetch.post("http://httpbin.org/post", /* `String */[
              -976970511,
              "datathings"
            ])));

/*  Not a pure module */
